global:
  imageRepositoryUrl: someacr.azurecr.io

frontend:
  image:
    tag: "imageTag"
    pullPolicy: IfNotPresent
  service:
    type: ClusterIP
    port: 80
  replicaCount: 1
  autoscaling:
    enabled: false
  keyedVars:
    backendHost: http://backendHostBaseUrl