trigger:
  branches:
    include:
      - "dev"
  paths:
    include:
      - "src/Services/Frontend"

variables:
  - group: vg-aks

pool:
  vmImage: ubuntu-latest

stages:
  - stage: Set_variables
    displayName: Set variables
    jobs:      
      - job: Set_vars
        steps:
          - task: PowerShell@2
            displayName: Remove refs/tags from branch path and set pipeline variable
            inputs:
              targetType: 'inline'
              script: |
                $tagName = "$(Build.SourceBranch)" -replace "refs/tags/",""
                Write-Host "##vso[task.setvariable variable=tagName;]$tagName"
                Write-Host "Setting pipeline variable tagName to $tagName"
  - stage: Docker_CI
    displayName: Docker CI
    jobs:      
      - job: Docker
        variables:
        - name: dockerfilePath
          value: "**/src/Services/Accommodation/Accommodation.Api/Dockerfile"
        steps:
          - template: ../common/ci-docker-acr-steps.yaml
  - stage: Dev_CD
    displayName: Dev CD
    dependsOn: Docker_CI
    condition: succeeded()
    jobs:
      - deployment: dev_helm
        displayName: Deploy helm chart to Dev AKS
        environment: dev
        variables:
          - group: helm-dev
        strategy:
          runOnce:
            deploy:
              steps:
                - template: common/cd-helm-steps.yaml

