trigger:
  tags:
    include:
    - 'v*'

variables:
  tagVar: $(Build.SourceBranch)
  triggeredTag: ${{replace(variables['tagVar'], 'refs/tags/', '')}}
  tag2: ${{ replace('$(tagVar)','refs/tags/','aaa') }}

pool:
  vmImage: ubuntu-latest

steps:
- script: echo the tag that called this is called $(triggeredTag)
  displayName: 'Run a one-line script'
- script: echo the tag that called this is called $(tag2)
  displayName: 'Run a one-line script2'
- script: echo the tag that called this is called ${{ replace('$(Build.SourceBranch)','refs/tags/','bbb') }}
  displayName: 'Run a one-line script3'

- script: |
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml
  displayName: 'Run a multi-line script!'

- task: PowerShell@2
  displayName: Remove refs/tags from branch path and set pipeline variable
  inputs:
    targetType: 'inline'
    script: |
      $tagName = "$(Build.SourceBranch)" -replace "refs/tags/",""
      Write-Host "##vso[task.setvariable variable=BRANCH_PATH;]$branchSourcePath"
      Write-Host "Setting pipeline variable BRANCH_PATH to $branchSourcePath"

