trigger:
  tags:
    include:
    - 'v*'

variables:
  triggeredTag: $[replace('$(Build.SourceBranch)'', '/refs/tags/', '')]

pool:
  vmImage: ubuntu-latest

steps:
- script: echo the tag that called this is called $(triggeredTag)
  displayName: 'Run a one-line script'

- script: |
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml
  displayName: 'Run a multi-line script'
  