trigger:
  branches:
    include:
      - "dev"
  paths:
    include:
      - "src/Services/Frontend"

variables:
  - group: vg-common
  #- group: vg-serviceConnections
  # Individual variables
  - name: acrRepository
    value: frontend-dev
  - name: dockerfilePath
    value: "**/src/Services/Frontend/Dockerfile"
  - name: imageTagVariableName
    value: frontend_imageTag

pool:
  vmImage: ubuntu-latest

stages:
  - stage: Docker_CI
    displayName: Docker CI
    jobs:
      - job: Docker
        steps:
          - template: common/ci-docker-acr-steps.yaml
  # DEV
  - stage: Dev_CI
    displayName: Dev CI
    dependsOn: Docker_CI
    condition: succeeded()
    jobs:
      - deployment: dev_ci
        displayName: Update variables
        environment: vg-dev
        variables:
          - group: helm-dev
        strategy:
          runOnce:
            deploy:
              steps:
                - template: common/ci-update-vargroup.yaml
  - stage: Dev_CD
    displayName: Dev CD
    dependsOn: Dev_CI
    condition: succeeded()
    jobs:
      - deployment: dev_helm
        displayName: Deploy helm chart to Dev AKS
        environment: dev
        variables:
          - group: helm-dev
        strategy:
          runOnce:
            deploy:
              steps:
                - template: common/cd-helm-steps.yaml