trigger:
  tags:
    include:
    - 'v*'

variables:
  tagVar: $(Build.SourceBranch)
  triggeredTag: ${{replace(variables['tagVar'], 'refs/tags/', '')}}
  tag2: ${{ replace('$(tagVar)','refs/tags/','aaa') }}

pool:
  vmImage: ubuntu-latest

stages:
  - stage: Set_variables
    displayName: Set variables
    jobs:      
      - job: Set_vars
        steps:
          - task: PowerShell@2
            displayName: Remove refs/tags from branch path and set pipeline variable
            inputs:
              targetType: 'inline'
              script: |
                $tagName = "$(Build.SourceBranch)" -replace "refs/tags/",""
                Write-Host "##vso[task.setvariable variable=tagName;]$tagName"
                Write-Host "Setting pipeline variable tagName to $tagName"
  - stage: Docker_CI
    displayName: Docker CI
    jobs:      
      - job: Docker
        variables:
        - name: dockerfilePath
          value: "**/src/Services/Accommodation/Accommodation.Api/Dockerfile"
        steps:
          - template: ../common/ci-docker-acr-steps.yaml

